language: node_js
node_js:
  - "10.12"
  - "9.11"
  - "8.12"
  - "7.10"
  - "6.14"
  # - "5.12"
  # - "4.9"
  # - "0.12"
  # - "0.11"
  # - "0.10"
  # - "iojs"
cache:
  directories:
    - "node_modules"
