environment:
  matrix:
  # node.js
  - nodejs_version: "7.10"
  - nodejs_version: "6.11"
  - nodejs_version: "5.12"
  - nodejs_version: "4.8"
  - nodejs_version: "0.12"
  - nodejs_version: "0.11"
  - nodejs_version: "0.10"
  # io.js
  - nodejs_version: "1.0"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

# Don't actually build.
build: off
